### ISSUE TITLE
Selects Previous Day in Month View

### ISSUE THREAD

**Issue by seesemichaelj** [KinToday/kin-web-client#25] opened 2017-04-24 22:35 UTC
I'm not sure if this is by design, but it is counter-intuitive to me. When you're in the Month View, and you select a day to make an event, it starts making the event in the previous day.

**Comment by yannperson** [comment] 2017-04-25 06:17
Hi Michael,
I tried to reproduce the issue you describe but couldn't come up with the behaviour you describe.
![screenshot 2017-04-25 08 16 06](https://cloud.githubusercontent.com/assets/17596102/25371164/7dfe03e8-298f-11e7-8eec-25575276b627.png)

Do you have a screenshot to share? And what's your setup (browser/os/timezone)?

**Comment by yperson** [comment] 2017-04-25 06:20
Hi Michael,
I tried to reproduce the issue you describe but couldn't come up with the behaviour you describe.

![screenshot 2017-04-25 08 16 06](https://cloud.githubusercontent.com/assets/708443/25371246/049a8e08-2990-11e7-84d9-fa7135372aff.png)

Do you have a screenshot to share? And what's your setup (browser/os/timezone)?

**Comment by seesemichaelj** [comment] 2017-04-25 14:34
Thanks for the swift response. I'm running Windows 10 and Ubuntu 16 (happens on both) with Chrome 57.0.2987.133

I tried disabling all of my extensions and it still had the issue. See the attached GIF.

![kin_issue_25](https://cloud.githubusercontent.com/assets/549323/25390856/b55b13ea-29a2-11e7-873b-c3a7a5af7390.gif)

**Comment by seesemichaelj** [comment] 2017-04-30 22:07
I determined the source of the error. The host OS timezone is different than the application. My OS timezone is EDT (America/New_York), but I had incorrectly selected the CEST (Europe/Paris) timezone in Kin. My personal issue is resolved, but I believe this is incorrect behavior.

I'm also seeing todoist elements imported on the day after they are defined in Todoist even after fixing the timezone in Kin, disconnecting Todoist and reconnecting.

**Comment by zowesiouff** [comment] 2017-05-05 12:37
> I determined the source of the error. The host OS timezone is different than the application. My OS timezone is EDT (America/New_York), but I had incorrectly selected the CEST (Europe/Paris) timezone in Kin. My personal issue is resolved, but I believe this is incorrect behavior.

in theory, on your first login, we try to guess your timezone (some browsers don't give us the ability to get your OS timezone. Do you think something went wrong there (or maybe we should display more prominently that we guessed a timezone ?), or did you simply forgot that you were in the CEST timezone?

> I'm also seeing todoist elements imported on the day after they are defined in Todoist even after fixing the timezone in Kin, disconnecting Todoist and reconnecting.

Yep, I haven't had time to dig again on this issue. From my last deep dive, Todoist seems to offset the dates in its UI by the timezone used in their settings, which yields some funny results in Kin, because we expect providers to give us the "absolute" dates ( with tz data ) when we ask for events. Hopefully, I'll be able to fix this soon-ish.

**Comment by seesemichaelj** [comment] 2017-05-07 06:03
I opened a new account on my phone to test the timezones guess as I don't remember (also to test another platform. I'm running Android with Chrome. It picked CEST instead of EDT after a Google account sign up.

No I did not forget I was in CEST; I don't live in Europe haha. I'm guessing the guess is not right. I can take a look at the code and see if I can test further.

**Comment by seesemichaelj** [comment] 2017-05-07 06:10
I also opened issue #27 to track the Todoist issue

**Comment by seesemichaelj** [comment] 2017-05-07 20:48
Quickly looking at the code, at src/client/main.jsx:65, it checks to see if the timezone is empty in the user_config. Looking at src/client/utils.js:33, it appears that it's set to Europe/Paris (aka CEST) by default. I'm guessing that the guess never takes place...

**Comment by zowesiouff** [comment] 2017-05-07 22:13
You're right, it should be fixed by f3fdd948bea946a8cd94e729122148d8cc28f3da 

I still default to `Europe/Paris` but only in the case where the guess fails completely.

**Comment by zowesiouff** [comment] 2017-05-07 22:15
Since #27 is tracking Todoist issue, I'll close this, feel free to reopen if I overlook something :)

**Closed** 2017-05-07 22:15 UTC

**Comment by seesemichaelj** [comment] 2017-05-07 22:42
I verified that f3fdd94 fixed this issue. Thanks for the help!
